routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/posts', 'HomeController@findPosts')->name('posts.find');
Route::post('/email/send', 'HomeController@sendEmail')->name('email.send');

Route::group(['prefix' => 'admin'], function() {
    Auth::routes(['register' => false, 'verify' => false, 'reset' => false]);

    Route::namespace('Admin')->middleware('auth')->group(function() {
        Route::get('/', 'HomeController@index')->name('admin.index');
        Route::get('/dt/post/data', 'PostController@datatableData')->name('post.datatable.data');
        Route::resource('/posts', 'PostController')->except(['index', 'show', 'create']);
    });
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    /**
     * Prepare a date for array / JSON serialization.
     *
     * @param  \DateTimeInterface  $date
     * @return string
     */
    protected function serializeDate(\DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PostRequest;
use App\Post;
use DataTables;
use Image;
use Illuminate\Support\Facades\Storage;
use App\Enum\PostCategoryEnum;
use Illuminate\Http\UploadedFile;

class PostController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        // File upload & merge if second image is present
        $imagePath = $this->handleImageUpload($request->file('main_image'), $request->file('second_image'));

        $post = new Post();

        $post->description = $request->description;
        $post->category = $request->category;
        $post->image = $imagePath;

        $post->save();

        return response()->json(array(
            'status' => true,
            'message' => 'Publication enregistrée'
        ));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return response()->json(array(
            'html' => view('admin.post.form-update', 
                array('post' => $post, 'postCategories' => PostCategoryEnum::getAll())
            )->render()
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {
        if ($request->hasFile('main_image')) {
            // Upload file
            $imagePath = $request->file('main_image')->store('posts', 'public');

            $post->image = $imagePath;
        }

        if ($request->has('description')) {
            $post->description = $request->description;
        }

        if ($request->has('category')) {
            $post->category = $request->category;
        }

        $post->save();

        return response()->json(array(
            'status' => true,
            'message' => 'Publication modifiée'
        ));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return response()->json([
            'status' => true,
            'message' => 'Publication supprimée'
        ]);
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function datatableData()
    {
        return Datatables::of(Post::all())
            ->addColumn('actions', "admin.datatable.post-actions")
            ->rawColumns(['actions'])
            ->editColumn('created_at', function ($request) {
                return $request->created_at->format('d/m/Y H:i');
            })
            ->editColumn('category', function ($request) {
                return PostCategoryEnum::getName($request->category);
            })
            ->make(true);
    }

    private function handleImageUpload(UploadedFile $mainImage, ?UploadedFile $secondImage) 
    {
        // If only main image
        if (!$secondImage) {
            return $mainImage->store('posts', 'public');
        }

        // Else => create new image from the others
        $mainImageObject = Image::make($mainImage);
        $secondImageObject = Image::make($secondImage);

        // Reduce height of the highest image and find new image height
        if ($mainImageObject->height() < $secondImageObject->height()) {
            $newImageHeight = $mainImageObject->height();
            $secondImageObject->heighten($mainImageObject->height());
        } else {
            $newImageHeight = $secondImageObject->height();
            $mainImageObject->heighten($secondImageObject->height());
        }

        $newImageWidth = $mainImageObject->width() + $secondImageObject->width();

        $newImage = Image::canvas($newImageWidth, $newImageHeight);
        $newImage->insert($mainImageObject);
        $newImage->insert($secondImageObject, 'right');
        $newImage->encode('jpg');

        $hash = md5($newImage->__toString());
        $filePath = 'posts/' . $hash . '.jpg';

        Storage::disk('public')->put($filePath, $newImage);

        return $filePath;
    }
}

resources/views/admin/post/form-update.blade.php
<div class="modal-body">
    <form class="form-update-post">
        <div class="form-group">
            <label for="update-category" class="col-form-label">Catégorie</label>
            <select class="form-control" id="update-category">
                @foreach ($postCategories as $slug => $name)
                    <option value="{{ $slug }}" {{ $slug === $post->category ? 'selected' : null }}>{{ $name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="update-description" class="col-form-label">Description</label>
            <textarea class="form-control" id="update-description" rows="3" placeholder="Description">{{ $post->description }}</textarea>
        </div>
        
        <div class="form-group">
            <label for="update-main-image">Image</label>
            <input type="file" class="form-control-file" id="update-main-image" accept="image/*">
        </div>

        <div class="form-group">
            <label for="update-second-image">Image complémentaire (optionnel)</label>
            <input type="file" class="form-control-file" id="update-second-image" accept="image/*">
        </div>
    </form>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">
        <i class="fas fa-times"></i>
        Fermer
    </button>
    <button type="button" class="btn btn-success btn-sm update-post" data-url="{{ route('posts.update', $post->id) }}">
        <i class="fas fa-save"></i>
        Enregistrer
    </button>
</div>

resources/views/admin/post/modal-create.blade.php
<div class="modal fade" id="modal-post-create" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Créer une publication</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="category" class="col-form-label">Catégorie</label>
                        <select class="form-control" id="category">
                            @foreach ($postCategories as $slug => $name)
                                <option value="{{ $slug }}">{{ $name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="description" class="col-form-label">Description</label>
                        <textarea class="form-control" id="description" rows="3" placeholder="Description"></textarea>
                    </div>
                    
                    <div class="form-group">
                        <label for="main-image">Image</label>
                        <input type="file" class="form-control-file" id="main-image" accept="image/*">
                    </div>

                    <div class="form-group">
                        <label for="second-image">Image complémentaire (optionnel)</label>
                        <input type="file" class="form-control-file" id="second-image" accept="image/*">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">
                    <i class="fas fa-times"></i>
                    Fermer
                </button>
                <button type="button" class="btn btn-success btn-sm create-post" data-url="{{ route('posts.store') }}">
                    <i class="fas fa-save"></i>
                    Enregistrer
                </button>
            </div>
        </div>
    </div>
</div>